### PR TITLE
Report

### LINKED ISSUE #2: Create report
After resolving some doubts (on 2024/11/21 meeting), we should provide a report by next week.
Relevant info from the minutes at https://github.com/pharmaR/regulatory-r-repo-wg/issues/103:

> Lluis is summarizing information of riskmetric. Next week, we can expect a first draft of a Val Report.
> Template for report: [insightsengineering/thevalidatoR](https://github.com/insightsengineering/thevalidatoR)
> Example report [insightsengineering/thevalidatoR@main/readme_files/report-0.1-admiral.pdf](https://github.com/insightsengineering/thevalidatoR/blob/main/readme_files/report-0.1-admiral.pdf?rgh-link-date=2024-11-21T12%3A57%3A56Z)

### PR DESCRIPTION
**Pull request by llrs**
Creating the report, takes the template from [insightsengineering/thevalidatoR](https://github.com/insightsengineering/thevalidatoR)

Closes #2

### CODE REVIEW

**Comment by llrs-roche** [comment]
This reports works but there are some corner cases to fix:

- [ ] Deal with riskmetric failures (see #3 )
- [ ] Parametrize which riskmetric assessment to perform
- [ ] add [branding](https://quarto.org/docs/authoring/brand.html) to the quarto template (requires quarto 1.6)
- [ ] Be more selective with what to include: I've been very exhaustive with R session, environment and options.

**Comment by Zhenglei-BCS** [comment]
Could I edit the documentation directly? 
The assessment function is designed to process an object created by the pkg_assess() function from the riskmetric package. The function takes this assessment object and converts it into a simplified data.frame without scoring the assessment.

**Comment by llrs-roche** [comment]
Yes, feel free to commit and push to the branch! I took too much shortcuts and neglected a bit the documentation.

I haven't tested building the package or generating vignettes as some of them assume certain data or took too long (until I discovered that riskmetric was checking the package again) . Would you like to work on that? 

1. Great idea! This will make easier handling errors or failures.
2. So we could have one report for individual package and one general for the whole repository? This looks like a good idea. Please go ahead on this. Do you want to be on the meeting with Pavel on Monday morning?

**Comment by Zhenglei-BCS** [comment]
> I haven't tested building the package or generating vignettes as some of them assume certain data or took too long (until I discovered that riskmetric was checking the package again) . Would you like to work on that?

Not sure about this vignettes, I will see what I can do. 

> 1. Great idea! This will make easier handling errors or failures.
> 2. So we could have one report for individual package and one general for the whole repository? This looks like a good idea. Please go ahead on this. Do you want to be on the meeting with Pavel on Monday morning?

Yes, one general for all packages, one for individual report (maybe also for a filtered list of packages based on the previous one) where the user can have more control on what criteria are used, what should be included in the report. I do have time on Monday, but I am not so good at coding and not sure how much I can contribute there. 

I feel we can merge the pull request and work on these afterwards, then create a new pull request.

**Pull request merged**
